name: Rust

on:
  push:
    branches: [ main ]
 # pull_request:
 #  branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
      
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
         name: oxidize-linux-x86_64
         path: target/release/oxidize
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: oxidize-linux-x86_64
          files: |
            target/release/oxidize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
          override: true

      - name: Build
        run: cargo build --all --release
        
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
         name: oxidize-windows-x86_64
         path: target/release/oxidize.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: oxidize-windows-x86_64
          files: target/release/oxidize.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
         name: oxidize-macos-x86_64
         path: target/release/oxidize
         
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: oxidize-macos-x86_64
          files: |
            target/release/oxidize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}